package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccessRights generated by hbm2java
 */
@Entity
@Table(name = "access_rights", catalog = "sme_development")
public class AccessRights implements java.io.Serializable {

	private int id;
	private AccessRightsMasterData accessRightsMasterData;
	private Organisation organisation;
	private Role role;
	private Boolean allowed;

	public AccessRights() {
	}

	public AccessRights(int id) {
		this.id = id;
	}

	public AccessRights(int id, AccessRightsMasterData accessRightsMasterData, Organisation organisation, Role role,
			Boolean allowed) {
		this.id = id;
		this.accessRightsMasterData = accessRightsMasterData;
		this.organisation = organisation;
		this.role = role;
		this.allowed = allowed;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "access_controll_type")
	public AccessRightsMasterData getAccessRightsMasterData() {
		return this.accessRightsMasterData;
	}

	public void setAccessRightsMasterData(AccessRightsMasterData accessRightsMasterData) {
		this.accessRightsMasterData = accessRightsMasterData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_type")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "allowed")
	public Boolean getAllowed() {
		return this.allowed;
	}

	public void setAllowed(Boolean allowed) {
		this.allowed = allowed;
	}

}
