package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccessRightsMasterData generated by hbm2java
 */
@Entity
@Table(name = "access_rights_master_data", catalog = "sme_development")
public class AccessRightsMasterData implements java.io.Serializable {

	private int id;
	private String accessRight;
	private Set<AccessRights> accessRightses = new HashSet<AccessRights>(0);
	private Set<AccessRights> accessRightses_1 = new HashSet<AccessRights>(0);

	public AccessRightsMasterData() {
	}

	public AccessRightsMasterData(int id) {
		this.id = id;
	}

	public AccessRightsMasterData(int id, String accessRight, Set<AccessRights> accessRightses,
			Set<AccessRights> accessRightses_1) {
		this.id = id;
		this.accessRight = accessRight;
		this.accessRightses = accessRightses;
		this.accessRightses_1 = accessRightses_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "access_right", length = 30)
	public String getAccessRight() {
		return this.accessRight;
	}

	public void setAccessRight(String accessRight) {
		this.accessRight = accessRight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessRightsMasterData")
	public Set<AccessRights> getAccessRightses() {
		return this.accessRightses;
	}

	public void setAccessRightses(Set<AccessRights> accessRightses) {
		this.accessRightses = accessRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessRightsMasterData")
	public Set<AccessRights> getAccessRightses_1() {
		return this.accessRightses_1;
	}

	public void setAccessRightses_1(Set<AccessRights> accessRightses_1) {
		this.accessRightses_1 = accessRightses_1;
	}

}
