package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Applicationoauthsetting generated by hbm2java
 */
@Entity
@Table(name = "applicationoauthsetting", catalog = "sme_development")
public class Applicationoauthsetting implements java.io.Serializable {

	private Long id;
	private String consumerKey;
	private String consumerSecret;
	private Date createdDate;
	private String callBackUrl;
	private Set<Oauthsession> oauthsessions = new HashSet<Oauthsession>(0);
	private Set<Oauthsession> oauthsessions_1 = new HashSet<Oauthsession>(0);

	public Applicationoauthsetting() {
	}

	public Applicationoauthsetting(String consumerKey, String consumerSecret, Date createdDate, String callBackUrl,
			Set<Oauthsession> oauthsessions, Set<Oauthsession> oauthsessions_1) {
		this.consumerKey = consumerKey;
		this.consumerSecret = consumerSecret;
		this.createdDate = createdDate;
		this.callBackUrl = callBackUrl;
		this.oauthsessions = oauthsessions;
		this.oauthsessions_1 = oauthsessions_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Consumer_key")
	public String getConsumerKey() {
		return this.consumerKey;
	}

	public void setConsumerKey(String consumerKey) {
		this.consumerKey = consumerKey;
	}

	@Column(name = "Consumer_Secret")
	public String getConsumerSecret() {
		return this.consumerSecret;
	}

	public void setConsumerSecret(String consumerSecret) {
		this.consumerSecret = consumerSecret;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CreatedDate", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CallBackURL")
	public String getCallBackUrl() {
		return this.callBackUrl;
	}

	public void setCallBackUrl(String callBackUrl) {
		this.callBackUrl = callBackUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationoauthsetting")
	public Set<Oauthsession> getOauthsessions() {
		return this.oauthsessions;
	}

	public void setOauthsessions(Set<Oauthsession> oauthsessions) {
		this.oauthsessions = oauthsessions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationoauthsetting")
	public Set<Oauthsession> getOauthsessions_1() {
		return this.oauthsessions_1;
	}

	public void setOauthsessions_1(Set<Oauthsession> oauthsessions_1) {
		this.oauthsessions_1 = oauthsessions_1;
	}

}
