package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Applicationproperties generated by hbm2java
 */
@Entity
@Table(name = "applicationproperties", catalog = "sme_development")
public class Applicationproperties implements java.io.Serializable {

	private Long applicationpropertiesId;
	private String name;
	private String value;
	private Character status;

	public Applicationproperties() {
	}

	public Applicationproperties(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public Applicationproperties(String name, String value, Character status) {
		this.name = name;
		this.value = value;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ApplicationpropertiesID", unique = true, nullable = false)
	public Long getApplicationpropertiesId() {
		return this.applicationpropertiesId;
	}

	public void setApplicationpropertiesId(Long applicationpropertiesId) {
		this.applicationpropertiesId = applicationpropertiesId;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "Status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
