package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BranchSchedule generated by hbm2java
 */
@Entity
@Table(name = "branch_schedule", catalog = "sme_development")
public class BranchSchedule implements java.io.Serializable {

	private Integer id;
	private Branch branch;
	private Integer weekDay;
	private String openTime;
	private String closeTime;

	public BranchSchedule() {
	}

	public BranchSchedule(Branch branch, Integer weekDay, String openTime, String closeTime) {
		this.branch = branch;
		this.weekDay = weekDay;
		this.openTime = openTime;
		this.closeTime = closeTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "week_day")
	public Integer getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(Integer weekDay) {
		this.weekDay = weekDay;
	}

	@Column(name = "open_time", length = 45)
	public String getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(String openTime) {
		this.openTime = openTime;
	}

	@Column(name = "close_time", length = 45)
	public String getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(String closeTime) {
		this.closeTime = closeTime;
	}

}
