package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BusinessTypeMasterdata generated by hbm2java
 */
@Entity
@Table(name = "business_type_masterdata", catalog = "sme_development")
public class BusinessTypeMasterdata implements java.io.Serializable {

	private int id;
	private BusinessCategoryMasterdata businessCategoryMasterdata;
	private String businessType;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Organisation> organisations_1 = new HashSet<Organisation>(0);

	public BusinessTypeMasterdata() {
	}

	public BusinessTypeMasterdata(int id) {
		this.id = id;
	}

	public BusinessTypeMasterdata(int id, BusinessCategoryMasterdata businessCategoryMasterdata, String businessType,
			Set<Organisation> organisations, Set<Organisation> organisations_1) {
		this.id = id;
		this.businessCategoryMasterdata = businessCategoryMasterdata;
		this.businessType = businessType;
		this.organisations = organisations;
		this.organisations_1 = organisations_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_category_id")
	public BusinessCategoryMasterdata getBusinessCategoryMasterdata() {
		return this.businessCategoryMasterdata;
	}

	public void setBusinessCategoryMasterdata(BusinessCategoryMasterdata businessCategoryMasterdata) {
		this.businessCategoryMasterdata = businessCategoryMasterdata;
	}

	@Column(name = "business_type", length = 256)
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessTypeMasterdata")
	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessTypeMasterdata")
	public Set<Organisation> getOrganisations_1() {
		return this.organisations_1;
	}

	public void setOrganisations_1(Set<Organisation> organisations_1) {
		this.organisations_1 = organisations_1;
	}

}
