package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientOffer generated by hbm2java
 */
@Entity
@Table(name = "client_offer", catalog = "sme_development")
public class ClientOffer implements java.io.Serializable {

	private Integer id;
	private Client client;
	private Offers offers;

	public ClientOffer() {
	}

	public ClientOffer(Client client, Offers offers) {
		this.client = client;
		this.offers = offers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_id")
	public Offers getOffers() {
		return this.offers;
	}

	public void setOffers(Offers offers) {
		this.offers = offers;
	}

}
