package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FeedbackSubdata generated by hbm2java
 */
@Entity
@Table(name = "feedback_subdata", catalog = "sme_development")
public class FeedbackSubdata implements java.io.Serializable {

	private Integer id;
	private Branch branch;
	private Client client;
	private ClientOrder clientOrder;
	private FeedbackMasterdata feedbackMasterdata;
	private String answer;

	public FeedbackSubdata() {
	}

	public FeedbackSubdata(Branch branch, Client client, ClientOrder clientOrder, FeedbackMasterdata feedbackMasterdata,
			String answer) {
		this.branch = branch;
		this.client = client;
		this.clientOrder = clientOrder;
		this.feedbackMasterdata = feedbackMasterdata;
		this.answer = answer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public ClientOrder getClientOrder() {
		return this.clientOrder;
	}

	public void setClientOrder(ClientOrder clientOrder) {
		this.clientOrder = clientOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public FeedbackMasterdata getFeedbackMasterdata() {
		return this.feedbackMasterdata;
	}

	public void setFeedbackMasterdata(FeedbackMasterdata feedbackMasterdata) {
		this.feedbackMasterdata = feedbackMasterdata;
	}

	@Column(name = "answer", length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
