package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FilterCustomerForoffer generated by hbm2java
 */
@Entity
@Table(name = "filter_customer_foroffer", catalog = "sme_development")
public class FilterCustomerForoffer implements java.io.Serializable {

	private Integer id;
	private Offers offers;
	private String filterCustomerType;

	public FilterCustomerForoffer() {
	}

	public FilterCustomerForoffer(Offers offers) {
		this.offers = offers;
	}

	public FilterCustomerForoffer(Offers offers, String filterCustomerType) {
		this.offers = offers;
		this.filterCustomerType = filterCustomerType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_id", nullable = false)
	public Offers getOffers() {
		return this.offers;
	}

	public void setOffers(Offers offers) {
		this.offers = offers;
	}

	@Column(name = "filter_customer_type", length = 20)
	public String getFilterCustomerType() {
		return this.filterCustomerType;
	}

	public void setFilterCustomerType(String filterCustomerType) {
		this.filterCustomerType = filterCustomerType;
	}

}
