package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "sme_development")
public class Media implements java.io.Serializable {

	private Integer id;
	private Organisation organisation;
	private byte[] file;
	private String fileType;
	private String fileName;
	private byte[] originalMedia;
	private Character imageType;

	public Media() {
	}

	public Media(Organisation organisation, byte[] file, String fileType, String fileName, byte[] originalMedia,
			Character imageType) {
		this.organisation = organisation;
		this.file = file;
		this.fileType = fileType;
		this.fileName = fileName;
		this.originalMedia = originalMedia;
		this.imageType = imageType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "file")
	public byte[] getFile() {
		return this.file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

	@Column(name = "file_type", length = 45)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "original_Media")
	public byte[] getOriginalMedia() {
		return this.originalMedia;
	}

	public void setOriginalMedia(byte[] originalMedia) {
		this.originalMedia = originalMedia;
	}

	@Column(name = "image_type", length = 1)
	public Character getImageType() {
		return this.imageType;
	}

	public void setImageType(Character imageType) {
		this.imageType = imageType;
	}

}
