package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oauthsession generated by hbm2java
 */
@Entity
@Table(name = "oauthsession", catalog = "sme_development")
public class Oauthsession implements java.io.Serializable {

	private Long id;
	private Applicationoauthsetting applicationoauthsetting;
	private String accessToken;
	private String accessTokenSecret;
	private Date createdDate;
	private byte[] consumerObject;
	private byte[] accessorObject;

	public Oauthsession() {
	}

	public Oauthsession(Applicationoauthsetting applicationoauthsetting, String accessToken, String accessTokenSecret,
			Date createdDate, byte[] consumerObject, byte[] accessorObject) {
		this.applicationoauthsetting = applicationoauthsetting;
		this.accessToken = accessToken;
		this.accessTokenSecret = accessTokenSecret;
		this.createdDate = createdDate;
		this.consumerObject = consumerObject;
		this.accessorObject = accessorObject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ApplicationOAuthSettingId")
	public Applicationoauthsetting getApplicationoauthsetting() {
		return this.applicationoauthsetting;
	}

	public void setApplicationoauthsetting(Applicationoauthsetting applicationoauthsetting) {
		this.applicationoauthsetting = applicationoauthsetting;
	}

	@Column(name = "Access_Token")
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "Access_Token_Secret")
	public String getAccessTokenSecret() {
		return this.accessTokenSecret;
	}

	public void setAccessTokenSecret(String accessTokenSecret) {
		this.accessTokenSecret = accessTokenSecret;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CreatedDate", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "ConsumerObject")
	public byte[] getConsumerObject() {
		return this.consumerObject;
	}

	public void setConsumerObject(byte[] consumerObject) {
		this.consumerObject = consumerObject;
	}

	@Column(name = "AccessorObject")
	public byte[] getAccessorObject() {
		return this.accessorObject;
	}

	public void setAccessorObject(byte[] accessorObject) {
		this.accessorObject = accessorObject;
	}

}
