package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfferType generated by hbm2java
 */
@Entity
@Table(name = "offer_type", catalog = "sme_development")
public class OfferType implements java.io.Serializable {

	private Integer id;
	private Organisation organisation;
	private String offerType;
	private Boolean event;
	private Boolean festival;
	private Date offerDate;
	private Set<Offers> offerses = new HashSet<Offers>(0);
	private Set<Offers> offerses_1 = new HashSet<Offers>(0);

	public OfferType() {
	}

	public OfferType(String offerType) {
		this.offerType = offerType;
	}

	public OfferType(Organisation organisation, String offerType, Boolean event, Boolean festival, Date offerDate,
			Set<Offers> offerses, Set<Offers> offerses_1) {
		this.organisation = organisation;
		this.offerType = offerType;
		this.event = event;
		this.festival = festival;
		this.offerDate = offerDate;
		this.offerses = offerses;
		this.offerses_1 = offerses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization_id")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "offer_type", nullable = false, length = 20)
	public String getOfferType() {
		return this.offerType;
	}

	public void setOfferType(String offerType) {
		this.offerType = offerType;
	}

	@Column(name = "event")
	public Boolean getEvent() {
		return this.event;
	}

	public void setEvent(Boolean event) {
		this.event = event;
	}

	@Column(name = "festival")
	public Boolean getFestival() {
		return this.festival;
	}

	public void setFestival(Boolean festival) {
		this.festival = festival;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "offer_date", length = 10)
	public Date getOfferDate() {
		return this.offerDate;
	}

	public void setOfferDate(Date offerDate) {
		this.offerDate = offerDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offerType")
	public Set<Offers> getOfferses() {
		return this.offerses;
	}

	public void setOfferses(Set<Offers> offerses) {
		this.offerses = offerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offerType")
	public Set<Offers> getOfferses_1() {
		return this.offerses_1;
	}

	public void setOfferses_1(Set<Offers> offerses_1) {
		this.offerses_1 = offerses_1;
	}

}
