package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OfferTemplate generated by hbm2java
 */
@Entity
@Table(name = "offer_template", catalog = "sme_development")
public class OfferTemplate implements java.io.Serializable {

	private Integer id;
	private Offers offers;
	private String emailSubject;
	private String emailTemplate;
	private String smsTemplate;

	public OfferTemplate() {
	}

	public OfferTemplate(Offers offers) {
		this.offers = offers;
	}

	public OfferTemplate(Offers offers, String emailSubject, String emailTemplate, String smsTemplate) {
		this.offers = offers;
		this.emailSubject = emailSubject;
		this.emailTemplate = emailTemplate;
		this.smsTemplate = smsTemplate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_id", nullable = false)
	public Offers getOffers() {
		return this.offers;
	}

	public void setOffers(Offers offers) {
		this.offers = offers;
	}

	@Column(name = "email_subject", length = 100)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "email_template", length = 500)
	public String getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(String emailTemplate) {
		this.emailTemplate = emailTemplate;
	}

	@Column(name = "sms_template", length = 200)
	public String getSmsTemplate() {
		return this.smsTemplate;
	}

	public void setSmsTemplate(String smsTemplate) {
		this.smsTemplate = smsTemplate;
	}

}
