package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name = "organisation", catalog = "sme_development")
public class Organisation implements java.io.Serializable {

	private Integer id;
	private BusinessTypeMasterdata businessTypeMasterdata;
	private String organisationName;
	private String adress1;
	private String adress2;
	private String city;
	private String state;
	private String phone;
	private String website;
	private String pincode;
	private String detailInfo;
	private Set<ClientReview> clientReviews = new HashSet<ClientReview>(0);
	private Set<ReferralMasterdata> referralMasterdatas = new HashSet<ReferralMasterdata>(0);
	private Set<TaxMasterdata> taxMasterdatas = new HashSet<TaxMasterdata>(0);
	private Set<Media> medias = new HashSet<Media>(0);
	private Set<OrderMasterdata> orderMasterdatas = new HashSet<OrderMasterdata>(0);
	private Set<ClientReview> clientReviews_1 = new HashSet<ClientReview>(0);
	private Set<Contact> contacts = new HashSet<Contact>(0);
	private Set<OrderMasterdata> orderMasterdatas_1 = new HashSet<OrderMasterdata>(0);
	private Set<ReferralMasterdata> referralMasterdatas_1 = new HashSet<ReferralMasterdata>(0);
	private Set<ServiceMasterdata> serviceMasterdatas = new HashSet<ServiceMasterdata>(0);
	private Set<Media> medias_1 = new HashSet<Media>(0);
	private Set<ServiceMasterdata> serviceMasterdatas_1 = new HashSet<ServiceMasterdata>(0);
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<AccessRights> accessRightses = new HashSet<AccessRights>(0);
	private Set<AccessRights> accessRightses_1 = new HashSet<AccessRights>(0);
	private Set<ApplicationUser> applicationUsers = new HashSet<ApplicationUser>(0);
	private Set<Branch> branches = new HashSet<Branch>(0);
	private Set<ApplicationUser> applicationUsers_1 = new HashSet<ApplicationUser>(0);
	private Set<Contact> contacts_1 = new HashSet<Contact>(0);
	private Set<OfferType> offerTypes = new HashSet<OfferType>(0);
	private Set<TaxMasterdata> taxMasterdatas_1 = new HashSet<TaxMasterdata>(0);
	private Set<Branch> branches_1 = new HashSet<Branch>(0);
	private Set<OfferType> offerTypes_1 = new HashSet<OfferType>(0);
	private Set<Client> clients_1 = new HashSet<Client>(0);

	public Organisation() {
	}

	public Organisation(BusinessTypeMasterdata businessTypeMasterdata, String organisationName, String adress1,
			String adress2, String city, String state, String phone, String website, String pincode, String detailInfo,
			Set<ClientReview> clientReviews, Set<ReferralMasterdata> referralMasterdatas,
			Set<TaxMasterdata> taxMasterdatas, Set<Media> medias, Set<OrderMasterdata> orderMasterdatas,
			Set<ClientReview> clientReviews_1, Set<Contact> contacts, Set<OrderMasterdata> orderMasterdatas_1,
			Set<ReferralMasterdata> referralMasterdatas_1, Set<ServiceMasterdata> serviceMasterdatas,
			Set<Media> medias_1, Set<ServiceMasterdata> serviceMasterdatas_1, Set<Client> clients,
			Set<AccessRights> accessRightses, Set<AccessRights> accessRightses_1, Set<ApplicationUser> applicationUsers,
			Set<Branch> branches, Set<ApplicationUser> applicationUsers_1, Set<Contact> contacts_1,
			Set<OfferType> offerTypes, Set<TaxMasterdata> taxMasterdatas_1, Set<Branch> branches_1,
			Set<OfferType> offerTypes_1, Set<Client> clients_1) {
		this.businessTypeMasterdata = businessTypeMasterdata;
		this.organisationName = organisationName;
		this.adress1 = adress1;
		this.adress2 = adress2;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.website = website;
		this.pincode = pincode;
		this.detailInfo = detailInfo;
		this.clientReviews = clientReviews;
		this.referralMasterdatas = referralMasterdatas;
		this.taxMasterdatas = taxMasterdatas;
		this.medias = medias;
		this.orderMasterdatas = orderMasterdatas;
		this.clientReviews_1 = clientReviews_1;
		this.contacts = contacts;
		this.orderMasterdatas_1 = orderMasterdatas_1;
		this.referralMasterdatas_1 = referralMasterdatas_1;
		this.serviceMasterdatas = serviceMasterdatas;
		this.medias_1 = medias_1;
		this.serviceMasterdatas_1 = serviceMasterdatas_1;
		this.clients = clients;
		this.accessRightses = accessRightses;
		this.accessRightses_1 = accessRightses_1;
		this.applicationUsers = applicationUsers;
		this.branches = branches;
		this.applicationUsers_1 = applicationUsers_1;
		this.contacts_1 = contacts_1;
		this.offerTypes = offerTypes;
		this.taxMasterdatas_1 = taxMasterdatas_1;
		this.branches_1 = branches_1;
		this.offerTypes_1 = offerTypes_1;
		this.clients_1 = clients_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_type_id")
	public BusinessTypeMasterdata getBusinessTypeMasterdata() {
		return this.businessTypeMasterdata;
	}

	public void setBusinessTypeMasterdata(BusinessTypeMasterdata businessTypeMasterdata) {
		this.businessTypeMasterdata = businessTypeMasterdata;
	}

	@Column(name = "organisation_name", length = 45)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "adress1", length = 45)
	public String getAdress1() {
		return this.adress1;
	}

	public void setAdress1(String adress1) {
		this.adress1 = adress1;
	}

	@Column(name = "adress2", length = 45)
	public String getAdress2() {
		return this.adress2;
	}

	public void setAdress2(String adress2) {
		this.adress2 = adress2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "website", length = 45)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "pincode", length = 6)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "detail_info", length = 1024)
	public String getDetailInfo() {
		return this.detailInfo;
	}

	public void setDetailInfo(String detailInfo) {
		this.detailInfo = detailInfo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ClientReview> getClientReviews() {
		return this.clientReviews;
	}

	public void setClientReviews(Set<ClientReview> clientReviews) {
		this.clientReviews = clientReviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ReferralMasterdata> getReferralMasterdatas() {
		return this.referralMasterdatas;
	}

	public void setReferralMasterdatas(Set<ReferralMasterdata> referralMasterdatas) {
		this.referralMasterdatas = referralMasterdatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<TaxMasterdata> getTaxMasterdatas() {
		return this.taxMasterdatas;
	}

	public void setTaxMasterdatas(Set<TaxMasterdata> taxMasterdatas) {
		this.taxMasterdatas = taxMasterdatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Media> getMedias() {
		return this.medias;
	}

	public void setMedias(Set<Media> medias) {
		this.medias = medias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OrderMasterdata> getOrderMasterdatas() {
		return this.orderMasterdatas;
	}

	public void setOrderMasterdatas(Set<OrderMasterdata> orderMasterdatas) {
		this.orderMasterdatas = orderMasterdatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ClientReview> getClientReviews_1() {
		return this.clientReviews_1;
	}

	public void setClientReviews_1(Set<ClientReview> clientReviews_1) {
		this.clientReviews_1 = clientReviews_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OrderMasterdata> getOrderMasterdatas_1() {
		return this.orderMasterdatas_1;
	}

	public void setOrderMasterdatas_1(Set<OrderMasterdata> orderMasterdatas_1) {
		this.orderMasterdatas_1 = orderMasterdatas_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ReferralMasterdata> getReferralMasterdatas_1() {
		return this.referralMasterdatas_1;
	}

	public void setReferralMasterdatas_1(Set<ReferralMasterdata> referralMasterdatas_1) {
		this.referralMasterdatas_1 = referralMasterdatas_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ServiceMasterdata> getServiceMasterdatas() {
		return this.serviceMasterdatas;
	}

	public void setServiceMasterdatas(Set<ServiceMasterdata> serviceMasterdatas) {
		this.serviceMasterdatas = serviceMasterdatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Media> getMedias_1() {
		return this.medias_1;
	}

	public void setMedias_1(Set<Media> medias_1) {
		this.medias_1 = medias_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ServiceMasterdata> getServiceMasterdatas_1() {
		return this.serviceMasterdatas_1;
	}

	public void setServiceMasterdatas_1(Set<ServiceMasterdata> serviceMasterdatas_1) {
		this.serviceMasterdatas_1 = serviceMasterdatas_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<AccessRights> getAccessRightses() {
		return this.accessRightses;
	}

	public void setAccessRightses(Set<AccessRights> accessRightses) {
		this.accessRightses = accessRightses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<AccessRights> getAccessRightses_1() {
		return this.accessRightses_1;
	}

	public void setAccessRightses_1(Set<AccessRights> accessRightses_1) {
		this.accessRightses_1 = accessRightses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ApplicationUser> getApplicationUsers() {
		return this.applicationUsers;
	}

	public void setApplicationUsers(Set<ApplicationUser> applicationUsers) {
		this.applicationUsers = applicationUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Branch> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branch> branches) {
		this.branches = branches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<ApplicationUser> getApplicationUsers_1() {
		return this.applicationUsers_1;
	}

	public void setApplicationUsers_1(Set<ApplicationUser> applicationUsers_1) {
		this.applicationUsers_1 = applicationUsers_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Contact> getContacts_1() {
		return this.contacts_1;
	}

	public void setContacts_1(Set<Contact> contacts_1) {
		this.contacts_1 = contacts_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OfferType> getOfferTypes() {
		return this.offerTypes;
	}

	public void setOfferTypes(Set<OfferType> offerTypes) {
		this.offerTypes = offerTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<TaxMasterdata> getTaxMasterdatas_1() {
		return this.taxMasterdatas_1;
	}

	public void setTaxMasterdatas_1(Set<TaxMasterdata> taxMasterdatas_1) {
		this.taxMasterdatas_1 = taxMasterdatas_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Branch> getBranches_1() {
		return this.branches_1;
	}

	public void setBranches_1(Set<Branch> branches_1) {
		this.branches_1 = branches_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OfferType> getOfferTypes_1() {
		return this.offerTypes_1;
	}

	public void setOfferTypes_1(Set<OfferType> offerTypes_1) {
		this.offerTypes_1 = offerTypes_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<Client> getClients_1() {
		return this.clients_1;
	}

	public void setClients_1(Set<Client> clients_1) {
		this.clients_1 = clients_1;
	}

}
