package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceMasterdata generated by hbm2java
 */
@Entity
@Table(name = "service_masterdata", catalog = "sme_development")
public class ServiceMasterdata implements java.io.Serializable {

	private Integer id;
	private Organisation organisation;
	private String serviceCategoty;
	private Set<ServiceOffered> serviceOffereds = new HashSet<ServiceOffered>(0);
	private Set<ServiceOffered> serviceOffereds_1 = new HashSet<ServiceOffered>(0);

	public ServiceMasterdata() {
	}

	public ServiceMasterdata(Organisation organisation, String serviceCategoty, Set<ServiceOffered> serviceOffereds,
			Set<ServiceOffered> serviceOffereds_1) {
		this.organisation = organisation;
		this.serviceCategoty = serviceCategoty;
		this.serviceOffereds = serviceOffereds;
		this.serviceOffereds_1 = serviceOffereds_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "service_categoty", length = 45)
	public String getServiceCategoty() {
		return this.serviceCategoty;
	}

	public void setServiceCategoty(String serviceCategoty) {
		this.serviceCategoty = serviceCategoty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceMasterdata")
	public Set<ServiceOffered> getServiceOffereds() {
		return this.serviceOffereds;
	}

	public void setServiceOffereds(Set<ServiceOffered> serviceOffereds) {
		this.serviceOffereds = serviceOffereds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceMasterdata")
	public Set<ServiceOffered> getServiceOffereds_1() {
		return this.serviceOffereds_1;
	}

	public void setServiceOffereds_1(Set<ServiceOffered> serviceOffereds_1) {
		this.serviceOffereds_1 = serviceOffereds_1;
	}

}
