package in.adcast.model;
// Generated 3 Feb, 2018 4:50:11 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceOffered generated by hbm2java
 */
@Entity
@Table(name = "service_offered", catalog = "sme_development")
public class ServiceOffered implements java.io.Serializable {

	private Integer id;
	private Branch branch;
	private ServiceMasterdata serviceMasterdata;
	private String serviceName;
	private String pricingTime;
	private String treatmentType;
	private String availableFor;
	private String extraTimeType;
	private Double durationInHrs;
	private BigDecimal price;
	private BigDecimal specialPrice;
	private BigDecimal discount;
	private Double tax;
	private Set<SubOrder> subOrders = new HashSet<SubOrder>(0);
	private Set<SubOrder> subOrders_1 = new HashSet<SubOrder>(0);

	public ServiceOffered() {
	}

	public ServiceOffered(Branch branch, ServiceMasterdata serviceMasterdata, String serviceName, String pricingTime,
			String treatmentType, String availableFor, String extraTimeType, Double durationInHrs, BigDecimal price,
			BigDecimal specialPrice, BigDecimal discount, Double tax, Set<SubOrder> subOrders,
			Set<SubOrder> subOrders_1) {
		this.branch = branch;
		this.serviceMasterdata = serviceMasterdata;
		this.serviceName = serviceName;
		this.pricingTime = pricingTime;
		this.treatmentType = treatmentType;
		this.availableFor = availableFor;
		this.extraTimeType = extraTimeType;
		this.durationInHrs = durationInHrs;
		this.price = price;
		this.specialPrice = specialPrice;
		this.discount = discount;
		this.tax = tax;
		this.subOrders = subOrders;
		this.subOrders_1 = subOrders_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_categoty_id")
	public ServiceMasterdata getServiceMasterdata() {
		return this.serviceMasterdata;
	}

	public void setServiceMasterdata(ServiceMasterdata serviceMasterdata) {
		this.serviceMasterdata = serviceMasterdata;
	}

	@Column(name = "service_name", length = 45)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "pricing_time", length = 45)
	public String getPricingTime() {
		return this.pricingTime;
	}

	public void setPricingTime(String pricingTime) {
		this.pricingTime = pricingTime;
	}

	@Column(name = "treatment_type", length = 45)
	public String getTreatmentType() {
		return this.treatmentType;
	}

	public void setTreatmentType(String treatmentType) {
		this.treatmentType = treatmentType;
	}

	@Column(name = "available_for", length = 45)
	public String getAvailableFor() {
		return this.availableFor;
	}

	public void setAvailableFor(String availableFor) {
		this.availableFor = availableFor;
	}

	@Column(name = "extra_time_type", length = 45)
	public String getExtraTimeType() {
		return this.extraTimeType;
	}

	public void setExtraTimeType(String extraTimeType) {
		this.extraTimeType = extraTimeType;
	}

	@Column(name = "duration_in_hrs", precision = 22, scale = 0)
	public Double getDurationInHrs() {
		return this.durationInHrs;
	}

	public void setDurationInHrs(Double durationInHrs) {
		this.durationInHrs = durationInHrs;
	}

	@Column(name = "price", precision = 9)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "special_price", precision = 9)
	public BigDecimal getSpecialPrice() {
		return this.specialPrice;
	}

	public void setSpecialPrice(BigDecimal specialPrice) {
		this.specialPrice = specialPrice;
	}

	@Column(name = "discount", precision = 9)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "tax", precision = 22, scale = 0)
	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceOffered")
	public Set<SubOrder> getSubOrders() {
		return this.subOrders;
	}

	public void setSubOrders(Set<SubOrder> subOrders) {
		this.subOrders = subOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceOffered")
	public Set<SubOrder> getSubOrders_1() {
		return this.subOrders_1;
	}

	public void setSubOrders_1(Set<SubOrder> subOrders_1) {
		this.subOrders_1 = subOrders_1;
	}

}
